### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by amilajack** [JamesTheHacker/Neuron#3]
It doesnt look like travis ci is enabled:

https://travis-ci.org/JamesTheHacker/Neuron

This isn't showing anything to me.

**Comment by JamesTheHacker** [comment]
It's showing the following for me, but I haven't done any commit since enabling it:

![image](https://cloud.githubusercontent.com/assets/19844560/17668547/b053e646-6301-11e6-9d23-ef88c756233b.png)

Will dig into this now.

**Comment by JamesTheHacker** [comment]
What are you seeing? Nothing at all? I'm getting very slow loading times and blank pages most of the time.

**Comment by JamesTheHacker** [comment]
Looks to be working this end :)

**Comment by amilajack** [comment]
It works fine for me now.
