### ISSUE TITLE
Question about JS

### ISSUE THREAD

**Issue by AlienFX** [JamesTheHacker/Neuron#4]
Hey,
I added the following file: /app/js/interface.js but impossible to load it.. ?!
Can you tell me if I need to add some config inside webpack.config.babbel.js for example or something else? 
I want to pack it in the output file /app/dist/app.js
Thank you in advance
Best regards

**Comment by JamesTheHacker** [comment]
I think your path is correct. It should be `./app/js/interface.js`. I am about to update the repo with an example, just incase others face the same issue.

**Comment by ghost** [comment]
Mishu who was the same problem in my opinion of your kind regards David is your responsibility also I don't see it as well but Remember what I need some advice from this group is not working properly configured form notifications please see my heart is not the same as a whole time for us

Sent from Yahoo Mail on Android 

  On মঙ্গল, আগস্ট ১৬, ২০১৬ at ৪:৪৪ pm, JamesTheHackernotifications@github.com wrote:  
I think your path is correct. It should be ./app/js/interface.js. I am about to update the repo with an example, just incase others face the same issue.

**Comment by JamesTheHacker** [comment]
Sorry, I didn't understand your last response.

**Comment by AlienFX** [comment]
What the hell, I didn't understand too.
Thank you for your answer, can you add too an example for the first react component ?
Write Hello World in the div id="app"

Just in case, I change your webpack.config and set : 

```
{
          test: /\.css$/,
          loader: 'style!css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]',
          include: [
            path.resolve(__dirname, 'app/css'),
          ] 
}
```

Do you think it's possible to mix scss AND css modules ?

Thank you :)
Flo

**Comment by JamesTheHacker** [comment]
I have updated the repo with a JS example. I haven't added a react example as I only just read this message after pushing. I will add an example today though :)

**Comment by JamesTheHacker** [comment]
React example added.
